### PR TITLE
Attempt to fix h13i32maru/esdoc#11

### PR DESCRIPTION
**Pull request by mmoss**
Attempt to resolve the issue(s) outlined in h13i32maru/esdoc#11 directly in the ES6 source (rather than in the distribution/built files).

### CODE REVIEW

**Comment by h13i32maru** [comment]
@mmoss Hi, thank you for this PR!
I have to fix the issue fundamentally. So, please wait just a little more :sweat_drops:

**Comment by mmoss** [comment]
Will do, this is a blocking issue for a project using ES6--this is a great tool, can't wait to see this resolved. :+1: 

Please let me know if there's anything I can do to help out.

**Comment by h13i32maru** [comment]
@mmoss ESDoc head revision fixes the issue. You can use it with following commands.

```
git clone git@github.com:h13i32maru/esdoc.git
cd esdoc/
npm install
npm run test
npm run build
npm install -g ./
esdoc -h
```

But if you have other problem, please post minimum codes that occur problem.

**Comment by mmoss** [comment]
It turns out the error error I was seeing below was caused by the usage of `@instance` & `@memberof` tags, where the `@memberof` didn't actually point to a file. Updating the comments (just removing the extranseous stuff I needed for JSDoc resolved this.)

> /usr/local/lib/node_modules/esdoc/out/src/Publisher/Builder/SearchIndexBuilder.js:106
> TypeError: Cannot read property 'kind' of undefined

**Comment by h13i32maru** [comment]
It is good :sparkles: Thank you!

**Pull request closed without merging**
